// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

import * as Jest from "bs-jest/lib/es6/src/jest.js";

Jest.test("should add one to one", (function () {
        return Jest.Expect[/* toEqual */11](2)(Jest.Expect[/* expect */0](2));
      }));

export {
  
}
/*  Not a pure module */
