// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");

Jest.test("should add one to one", (function () {
        return Jest.Expect[/* toEqual */12](2, Jest.Expect[/* expect */0](2));
      }));

/*  Not a pure module */
