// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("bs-jest/lib/js/src/jest.js");

Jest.test("it should return empty list initially", (function () {
        return Jest.Expect[/* toEqual */11](2)(Jest.Expect[/* expect */0](2));
      }));

/*  Not a pure module */
