// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

import * as App         from "./app.js";
import * as ReactDOMRe  from "reason-react/lib/es6/src/reactDOMRe.js";
import * as ReasonReact from "reason-react/lib/es6/src/reasonReact.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App.make("Anne", /* array */[])), "root");

export {
  
}
/*  Not a pure module */
