// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React      = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/reactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement("div", undefined, "Hello, world!"), "root");

/*  Not a pure module */
